Repository Team-Capple/Capple-Server, pull requests merged in 2024-04, with the labels that each got.

#80 [CHORE] 메일 인증 지원 도메인 변경
  src/main/java/com/server/capple/domain/mail/vo/MailDomain.java
Labels: enhancement

#84 [FEAT] 로그인 시 클라이언트 에러 핸들링 및 반환 데이터 정의
  src/main/java/com/server/capple/config/security/oauth/apple/client/AppleAuthClient.java
  src/main/java/com/server/capple/config/security/oauth/apple/service/AppleAuthServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/global/exception/errorCode/AppleOauthError.java
Labels: enhancement

#86 [FIX] MemberAnswerList 응답 객체 Getter 어노테이션 추가
  src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
Labels: 🐛bug

#88 [FEAT] 답변 조회 시 본인 답변 여부 데이터 추가
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
Labels: ✨feature

#91 Feat: #90 이메일 인증 화이트 리스트 기능 구현
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/domain/mail/repository/MailWhitelistRedisRepository.java
  src/main/java/com/server/capple/domain/mail/service/MailService.java
  src/main/java/com/server/capple/domain/mail/service/MailServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
Labels: enhancement

#98 [FIX] 태그 score가 1보다 낮아져도 삭제하지 않도록 수정
  src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
Labels: 🚨hotfix

#101 [FIX] 질문 Tag 저장 방식 변경
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/question/dao/QuestionInfoInterface.java
  src/main/java/com/server/capple/domain/question/entity/Question.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/domain/tag/controller/TagController.java
  src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
  src/main/java/com/server/capple/domain/tag/service/TagService.java
  src/main/java/com/server/capple/domain/tag/service/TagServiceImpl.java
  src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
  src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
  src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: enhancement

#108 [FIX] 빌드 워닝 해결
  build.gradle
  src/main/java/com/server/capple/domain/tag/dto/TagResponse.java
  src/main/java/com/server/capple/domain/tag/mapper/TagMapper.java
  src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
Labels: ⚒️chore

#105 [HOTFIX] 스케줄러 에러 핸들러 추가
  src/main/java/com/server/capple/config/SchedulerConfig.java
Labels: 🚨hotfix, 🐛bug

#113 [HOTFIX] 답변 삭제 후 isAnswered 업데이트
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
Labels: 🚨hotfix

#117 [HOTFIX] 프로필 이미지 NULL값으로 인한 작성한 답변 조회 에러 수정
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
  src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
Labels: 🚨hotfix
