Repository Team-Capple/Capple-Server, pull requests merged in 2024-03, with the labels that each got.

#19 [FEAT] 답변하기 API
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/server/capple/config/RedisConfig.java
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerRequest.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
  src/main/java/com/server/capple/domain/answer/entity/Answer.java
  src/main/java/com/server/capple/domain/answer/entity/AnswerHeart.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/member/entity/Member.java
  src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
  src/main/java/com/server/capple/domain/question/entity/Question.java
  src/main/java/com/server/capple/domain/question/entity/QuestionHeart.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/QuestionService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/domain/tag/Tag.java
  src/main/java/com/server/capple/domain/tag/controller/TagController.java
  src/main/java/com/server/capple/domain/tag/dto/TagResponse.java
  src/main/java/com/server/capple/domain/tag/entity/Tag.java
  src/main/java/com/server/capple/domain/tag/mapper/TagMapper.java
  src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
  src/main/java/com/server/capple/domain/tag/repository/TagRepository.java
  src/main/java/com/server/capple/domain/tag/service/TagService.java
  src/main/java/com/server/capple/domain/tag/service/TagServiceImpl.java
  src/main/java/com/server/capple/global/exception/errorCode/AnswerErrorCode.java
  src/main/java/com/server/capple/global/exception/errorCode/MemberErrorCode.java
  src/main/java/com/server/capple/global/exception/errorCode/QuestionErrorCode.java
  src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
  src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: ✨feature

#22 [FEAT] 질문 답변 상세 내용 뷰 API 구현
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerRequest.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
  src/main/java/com/server/capple/domain/answer/entity/Answer.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerHeartRedisRepository.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/domain/member/dto/MemberRequest.java
  src/main/java/com/server/capple/domain/member/dto/MemberResponse.java
  src/main/java/com/server/capple/domain/member/mapper/MemberMapper.java
  src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
  src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java
  src/main/java/com/server/capple/domain/question/mapper/QuestionMapper.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/domain/tag/mapper/TagMapper.java
  src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
  src/main/java/com/server/capple/domain/tag/repository/TagRepository.java
  src/main/java/com/server/capple/domain/tag/service/TagService.java
  src/main/java/com/server/capple/domain/tag/service/TagServiceImpl.java
  src/main/java/com/server/capple/global/exception/errorCode/AnswerErrorCode.java
  src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java
  src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
  src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
  src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: ✨feature

#33 [FEAT] S3 고아 이미지 삭제 기능 추가
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerHeartRedisRepository.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/domain/member/dto/MemberResponse.java
  src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
  src/main/java/com/server/capple/global/utils/S3ImageComponent.java
Labels: ✨feature

#42 [REFACTOR] 로그인 어노테이션 적용
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
  src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java
  src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
Labels: ♻️refactor

#63 [FEAT] 시간대를 서울로 변경
  src/main/java/com/server/capple/CappleApplication.java
Labels: 구현 개선 :t-rex:

#61 [REFACTOR] 회원가입, 인가 관련 기능 리팩터링
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/config/security/auth/CustomUserDetails.java
  src/main/java/com/server/capple/config/security/jwt/service/JwtService.java
  src/main/java/com/server/capple/config/security/jwt/service/JwtServiceImpl.java
  src/main/java/com/server/capple/domain/member/controller/MemberController.java
  src/main/java/com/server/capple/domain/member/entity/Member.java
  src/main/java/com/server/capple/domain/member/entity/Role.java
  src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
  src/main/java/com/server/capple/domain/member/service/MemberService.java
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
Labels: enhancement, ♻️refactor

#70 [HOTFIX] 이메일, 닉네임 체크 엔드포인트 필터링 제거
  src/main/java/com/server/capple/config/security/SecurityConfig.java
Labels: 🚨hotfix

#72 [FEAT]: #71 이메일 암호화 적용
  src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
Labels: 구현 개선 :t-rex:
