Repository Team-Capple/Capple-Server, pull requests merged in 2024-10, with the labels that each got.

#192 [FEAT] 무한스크롤의 중복 컨텐츠 문제 해결
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentService.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/domain/question/controller/QuestionController.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/QuestionService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
  src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
Labels: 🌟enhancement

#185 [FEAT] 게시글 조회 API DTO 변경
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
Labels: ✨feature

#198 [FIX] 게시글 댓글 정렬 기준 수정
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
Labels: 🐛bug

#200 [FIX] 질문별 조회시 답변 총 개수 반환 값 추가 및 lastIndex 생성 오류 수정
  src/main/java/com/server/capple/config/RedisConfig.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerCountService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
Labels: 🌟enhancement

#203 [FEAT] 게시글 단건 조회 API 구현
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentHeartRepository.java
Labels: ✨feature

#204 [RELEASE] 게시글 수정 API 구현, 게시글 댓글 정렬 기준 수정, 질문별 조회시 답변 총 개수 반환 값 추가, lastIndex 생성 오류 수정, 게시글 단건 조회 API 구현
  src/main/java/com/server/capple/config/RedisConfig.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerCountService.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dto/BoardRequest.java
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/entity/Board.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentHeartRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
Labels: 🏃🏻‍♀️‍➡️release

#207 [REFACTOR] Notification 조회 N+1 문제 해결
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
Labels: ♻️refactor

#209 [FIX] 노오프셋 페이징 기법으로 변경
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/domain/question/controller/QuestionController.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/QuestionService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
Labels: 🌟enhancement

#211 [REFACTOR] 답변 조회 N+1 문제 해결
  src/main/java/com/server/capple/domain/answer/dao/AnswerRDBDao.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
Labels: ♻️refactor

#213 [REFACTOR] 게시글 조회 N+1문제 해결
  src/main/java/com/server/capple/domain/board/dao/BoardInfoInterface.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
Labels: ♻️refactor

#214 [RELEASE] Notification, 답변, 게시글 조회 N+1 문제 해결, 노오프셋 페이징 기법으로 변경
  src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
  src/main/java/com/server/capple/domain/answer/dao/AnswerRDBDao.java
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dao/BoardInfoInterface.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/domain/question/controller/QuestionController.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/QuestionService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
Labels: 🏃🏻‍♀️‍➡️release

#218 [FIX] 화이트리스트에 있을 시 메일 발송을 하지 않도록 수정
  src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
Labels: 🌟enhancement

#220 [FIX] 인증메일 제목 변경
  src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
Labels: 🌟enhancement

#221 [RELEASE]
  src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
Labels: 🏃🏻‍♀️‍➡️release

#224 [FIX] 알림 회원 연관관계 설정 및 가입 전 알림 조회 차단
  src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
Labels: 🌟enhancement

#225 [RELEASE] 알림 회원 연관관계 설정 및 가입 전 알림 조회 차단
  src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
Labels: 🏃🏻‍♀️‍➡️release

#230 [HOTFIX] 질문, 댓글 원격 알림의 알림 사운드 설정
  src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
Labels: 🚨hotfix
