Repository Team-Capple/Capple-Server, pull requests merged in 2024-09, with the labels that each got.

#143 [REFACTOR] 좋아요 RDB로 구현
  src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/entity/Board.java
  src/main/java/com/server/capple/domain/board/entity/BoardHeart.java
  src/main/java/com/server/capple/domain/board/mapper/BoardHeartMapper.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java
  src/main/java/com/server/capple/domain/board/repository/BoardHeartRepository.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/dto/BoardCommentResponse.java
  src/main/java/com/server/capple/domain/boardComment/entity/BoardComment.java
  src/main/java/com/server/capple/domain/boardComment/entity/BoardCommentHeart.java
  src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentHeartMapper.java
  src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentHeartRedisRepository.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentHeartRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentService.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/question/controller/QuestionController.java
  src/main/java/com/server/capple/domain/question/repository/QuestionHeartRedisRepository.java
  src/main/java/com/server/capple/domain/question/service/QuestionService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/dummy/DummyController.java
  src/main/java/com/server/capple/dummy/DummyService.java
  src/main/java/com/server/capple/dummy/generate_dummy_data.sql
  src/test/java/com/server/capple/domain/answerComment/controller/AnswerCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: ✨feature

#147 [FEAT] 비즈니스 로직과 원격 알림 발송 로직 연결
  src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
  src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/boardSubscribeMember/entity/BoardSubscribeMember.java
  src/main/java/com/server/capple/domain/boardSubscribeMember/reposiotry/BoardSubscribeMemberRepository.java
  src/main/java/com/server/capple/domain/boardSubscribeMember/service/BoardSubscribeMemberService.java
  src/main/java/com/server/capple/domain/boardSubscribeMember/service/BoardSubscribeMemberServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/test/java/com/server/capple/config/apns/service/ApnsServiceImplTest.java
Labels: enhancement, 구현 개선 :t-rex:

#154 [FEAT] 알림 리스트 저장, 조회, 삭제 기능 구현
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
  src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java
  src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/scheduler/NotificationScheduler.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
Labels: enhancement, 구현 개선 :t-rex:

#144 [FEAT] 신고함 기능 구현(게시판)
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/domain/boardReport/controller/BoardReportController.java
  src/main/java/com/server/capple/domain/boardReport/dto/BoardReportRequest.java
  src/main/java/com/server/capple/domain/boardReport/dto/BoardReportResponse.java
  src/main/java/com/server/capple/domain/boardReport/entity/BoardReport.java
  src/main/java/com/server/capple/domain/boardReport/entity/BoardReportType.java
  src/main/java/com/server/capple/domain/boardReport/mapper/BoardReportMapper.java
  src/main/java/com/server/capple/domain/boardReport/repository/BoardReportRepository.java
  src/main/java/com/server/capple/domain/boardReport/service/BoardReportService.java
  src/main/java/com/server/capple/domain/boardReport/service/BoardReportServiceImpl.java
  src/main/java/com/server/capple/domain/report/repository/ReportRepository.java
  src/main/java/com/server/capple/global/exception/errorCode/BoardReportErrorCode.java
Labels: ✨feature

#146 [FEAT] 게시판 댓글 신고함 기능 구현
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/domain/answerComment/controller/AnswerCommentController.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/dto/BoardCommentResponse.java
  src/main/java/com/server/capple/domain/boardComment/entity/BoardComment.java
  src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
  src/main/java/com/server/capple/domain/boardCommentReport/controller/BoardCommentReportController.java
  src/main/java/com/server/capple/domain/boardCommentReport/dto/BoardCommentReportRequest.java
  src/main/java/com/server/capple/domain/boardCommentReport/dto/BoardCommentReportResponse.java
  src/main/java/com/server/capple/domain/boardCommentReport/entity/BoardCommentReport.java
  src/main/java/com/server/capple/domain/boardCommentReport/entity/BoardCommentReportType.java
  src/main/java/com/server/capple/domain/boardCommentReport/mapper/BoardCommentReportMapper.java
  src/main/java/com/server/capple/domain/boardCommentReport/repository/BoardCommentReportRepository.java
  src/main/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportService.java
  src/main/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportServiceImpl.java
  src/main/java/com/server/capple/global/exception/errorCode/BoardCommentReportErrorCode.java
  src/test/java/com/server/capple/domain/answerComment/controller/AnswerCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/domain/boardCommentReport/controller/BoardCommentReportControllerTest.java
  src/test/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: ✨feature

#158 [REFACTOR] RDB 좋아요 조회 방식 수정
  src/main/java/com/server/capple/config/security/SecurityConfig.java
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dao/BoardInfoInterface.java
  src/main/java/com/server/capple/domain/board/dto/BoardRequest.java
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/entity/Board.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/dao/BoardCommentInfoInterface.java
  src/main/java/com/server/capple/domain/boardComment/entity/BoardComment.java
  src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/boardReport/controller/BoardReportController.java
  src/main/java/com/server/capple/domain/boardReport/dto/BoardReportResponse.java
  src/main/java/com/server/capple/domain/boardReport/repository/BoardReportRepository.java
  src/main/java/com/server/capple/domain/boardReport/service/BoardReportService.java
  src/main/java/com/server/capple/domain/boardReport/service/BoardReportServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/domain/report/repository/ReportRepository.java
  src/main/java/com/server/capple/dummy/DummyService.java
  src/main/java/com/server/capple/dummy/generate_dummy_data.sql
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/domain/boardCommentReport/controller/BoardCommentReportControllerTest.java
  src/test/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportServiceTest.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: ♻️refactor

#160 [FEAT] 게시글, 댓글 목록 페이지네이션 구현
  src/main/java/com/server/capple/domain/board/controller/BoardController.java
  src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
  src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
  src/main/java/com/server/capple/domain/boardComment/dto/BoardCommentResponse.java
  src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
  src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentService.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
  src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
  src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
  src/test/java/com/server/capple/support/ControllerTestConfig.java
  src/test/java/com/server/capple/support/ServiceTestConfig.java
Labels: 🌟enhancement

#177 [FEAT] 회원가입 인증 메일 개선
  src/main/java/com/server/capple/CappleApplication.java
  src/main/java/com/server/capple/domain/mail/service/MailServiceImpl.java
  src/main/java/com/server/capple/domain/mail/service/MailUtil.java
  src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
  src/main/resources/templates/certCodeMail.html
Labels: 🌟enhancement

#174 [FEAT] 질문 생성/종료 원격 알림 구현 및 알림 엔티티 구성방식 변경
  src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
  src/main/java/com/server/capple/config/apns/service/ApnsService.java
  src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
  src/main/java/com/server/capple/domain/member/repository/DeviceTokenRedisRepository.java
  src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
  src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java
  src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
  src/main/java/com/server/capple/domain/notifiaction/entity/NotificationLog.java
  src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/com/server/capple/domain/notifiaction/scheduler/NotificationScheduler.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
  src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
  src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
  src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
Labels: 🌟enhancement

#179 feat: #178 원격 알림 양식 변경
  src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
  src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
Labels: 🌟enhancement

#187 [FEAT] csv 이용 질문 일괄 삽입 기능
  build.gradle
  src/main/java/com/server/capple/domain/question/controller/AdminQuestionController.java
  src/main/java/com/server/capple/domain/question/dto/internal/QuestionDto.java
  src/main/java/com/server/capple/domain/question/mapper/QuestionMapper.java
  src/main/java/com/server/capple/domain/question/repository/AdminQuestionRepository.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
Labels: 🌟enhancement

#189 [FEAT] 질문, 게시글 총 개수 반환
  src/main/java/com/server/capple/config/RedisConfig.java
  src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
  src/main/java/com/server/capple/domain/board/service/BoardCountService.java
  src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
  src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
  src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
  src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
  src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
  src/main/java/com/server/capple/domain/question/service/QuestionCountService.java
  src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/server/capple/global/common/SliceResponse.java
Labels: 🌟enhancement
